#!/usr/bin/env bash

# NOTE: This should be executed in CI only

cd test > /dev/null
source approvals.bash

export FUZZYCD_TTY_FORCE=1
../setup

# ideally, we would want to do 'source ~/.bashrc' but it is blocked in
# non-tty, so we:
#
#   a: source our file directly, which has a bypass via FUZZYCD_TTY_FORCE
#   b: verify that ~/.bashrc contains the source directive
#
source /usr/local/bin/fuzzycd

describe "cd is a function"
  [[ "$(type -t cd)" == "function" ]] || fail "Expected function got $(type -t cd)"

describe "~/.bashrc contains the source directive"
  grep -q fuzzycd ~/.bashrc || fail "Expected to find source directive in ~/.bashrc"

