#!/usr/bin/env bash

cd test > /dev/null
export APPROVALS_DIR="$PWD/approvals"
source approvals.bash

basedir="$PWD"
source ../fuzzy-cd
export FUZZYCD_HISTORY_FILE="$PWD/tmp/histfile"
rm -f "$FUZZYCD_HISTORY_FILE"
mkdir -p tmp/one/two
mkdir -p "$HOME/.fuzzy-cd"

context "when the shell is non-interactive"

  describe "cd is builtin"
    approve "type -t cd" "type_builtin"


context "when the shell is interactive"

  export FUZZYCD_TTY_FORCE=1
  source ../fuzzy-cd || return 0

  describe "cd is a function"
    approve "type -t cd" "type_function"

  describe "cd -h shows help"
    approve "cd -h"

  describe "cd -v shows version"
    approve "cd -v"

  describe "cd with a directory adds it to history"
    cd tmp/one/two > /dev/null
    [[ $PWD == *tmp/one/two ]] || fail "Expected tmp/one/twp, got $PWD"
    grep -q one/two "$FUZZYCD_HISTORY_FILE" || fail "Expected history file to contain one/two"

  describe "cd with a fuzzy string works"
    cd ontwo > /dev/null
    [[ $PWD == *tmp/one/two ]] || fail "Expected tmp/one/twp, got $PWD"


context "when the history file contains some entries"

  rm -f "$FUZZYCD_HISTORY_FILE"  
  cd /usr/local/bin > /dev/null
  cd /usr/local/lib > /dev/null
  cd /etc > /dev/null
  EDITOR="cat"

  describe "cd -s shows history file"
    approve "cd -s"

  describe "cd -e opens the history file"
    approve "cd -e"

  describe "cd -d DIR removes DIR from history"
    approve "cd -d /etc"
    approve "cd -s" "cd_s_after_delete"

  describe "cd -d removes current directory from history"
    cd /usr/local/lib
    approve "cd -d"
    approve "cd -s" "cd_s_after_delete2"

  cd "$basedir"
  rm -f "$FUZZYCD_HISTORY_FILE"  


context "when the FUZZYCD_MODE=non-interactive"

  export FUZZYCD_MODE=non-interactive
  rm -f "$FUZZYCD_HISTORY_FILE"
  cd /usr/local/bin > /dev/null
  cd /usr/local/lib > /dev/null

  describe "cd with a fuzzy string goes to bes match"
    approve "cd localb"

  cd "$basedir"
  rm -f "$FUZZYCD_HISTORY_FILE"
  unset FUZZYCD_MODE

