#!/usr/bin/env bash

if [[ -t 1 ]]; then
  unalias cd 2> /dev/null
  cd() {
    local histfile="$HOME/.fuzzy-cd-history"
    
    is_dirname() {
      if [[ -d "$1" ]]; then
        return 0
      
      elif [[ -n "$CDPATH" ]]; then
        cdpath=(${CDPATH//:/ })
        for path in "${cdpath[@]}"; do
          [[ -d "$path/$1" ]] && return 0
        done
      fi

      return 1
    }

    show_list_requested() {
      [[ "$1" == '-l' ]]
    }

    unhandled_command() {
      [[ $# == 0 || $1 == -* ]]
    }

    run_fzf() {
      fzf --query="$@" --select-1 --exit-0 --scheme=path --info=hidden --prompt="➜ cd " --preview="ls {}" --preview-window="border-left"
    }

    dir_search() {
      cat "$histfile" | run_fzf "$@"
    }

    remember_me() {
      grep -qxF "$PWD" "$histfile" || echo "$PWD" >> "$histfile"
    }

    chdir() {
      builtin cd "$@" && remember_me
    }

    [[ -f "$histfile" ]] || touch "$histfile"

    if show_list_requested "$@"; then
      dir_search
    elif unhandled_command "$@"; then
      chdir "$@"
    elif is_dirname "$1"; then
      chdir "$1"
    else
      chdir "$(dir_search "$@" || "$@")"
    fi
  }
fi