#!/usr/bin/env bash

# If not running interactively, don't do anything
# Bypass by setting FUZZYCD_TTY_FORCE
if [[ -z "$FUZZYCD_TTY_FORCE" ]]; then
  case $- in
    *i*) ;;
    *) return;;
  esac
fi

unalias cd 2> /dev/null
cd() {
  local version="0.1.1"
  local histfile=${FUZZYCD_HISTORY_FILE:-"$HOME/.fuzzy-cd-history"}
  
  is_dirname() {
    if [[ -d "$1" ]]; then
      return 0
    
    elif [[ -n "$CDPATH" ]]; then
      cdpath=("${CDPATH//:/ }")
      for path in "${cdpath[@]}"; do
        [[ -d "$path/$1" ]] && return 0
      done
    fi

    return 1
  }

  unhandled_command() {
    [[ $# == 0 || $1 == -* ]]
  }

  run_fzf() {
    # shellcheck disable=SC2145
    fzf --query="$@" --select-1 --exit-0 --scheme=path --info=hidden --prompt="➜ cd " --preview='ls {}' --preview-window="border-left"
  }

  dir_search() {
    run_fzf "$@" < "$histfile"
  }

  remember_me() {
    grep -qxF "$PWD" "$histfile" || echo "$PWD" >> "$histfile"
  }

  chdir() {
    builtin cd "$@" && remember_me
  }

  edit_histfile() {
    "${EDITOR:-cat}" "$histfile"
  }

  show_histfile() {
    cat "$histfile"
  }

  show_usage() {
    show_version
    echo ""
    echo "Usage:"
    echo "  cd DIR       change working directory"
    echo "  cd SEARCH    change working directory or show selection menu"
    echo "  cd -l        list history with fzf"
    echo "  cd -e        edit history file"
    echo "  cd -s        show history file"
    echo "  cd -v        show version"
    echo "  cd -h        show this help"
  }

  handle_command() {
    if unhandled_command "$@"; then
      chdir "$@"
    elif is_dirname "$1"; then
      chdir "$1"
    else    
      target=$(dir_search "$@")
      if [[ -n $target ]]; then
        chdir "$target"
      else
        chdir "$@"
      fi
    fi
  }

  run() {
    [[ -f "$histfile" ]] || touch "$histfile"

    case "$1" in
      "-l" ) dir_search ;;
      "-v" ) echo "fuzzy-cd $version" ;;
      "-e" ) edit_histfile ;;
      "-s" ) show_histfile ;;
      "-h" ) show_usage ;;
      *    ) handle_command "$@" ;;
    esac
  }  

  run "$@"
}
