# opcode: https://github.com/dannyben/opcode

## Linting

shellcheck: shellcheck setup fuzzycd && echo PASS
shfmt: shfmt -d -i 2 -ci setup fuzzycd && echo PASS
codespell: codespell

## Testing

test: op approval && op acceptance
approval: test/approve
acceptance: shellkin
