#!/usr/bin/env bash
set -euo pipefail

# === Setup SSI ===

echo "Initializing installer..."
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
cd "$tmpdir"
export PATH="$tmpdir:$PATH"

if command -v curl >/dev/null 2>&1; then
  curl -fSsL https://github.com/DannyBen/ssi/releases/download/v0.1.4/ssi -o ssi
elif command -v wget >/dev/null 2>&1; then
  wget -nv -O ssi https://github.com/DannyBen/ssi/releases/download/v0.1.4/ssi
else
  echo "Error: please install wget or curl, then try again" >&2
  exit 1
fi
chmod +x ssi

# === Install ===

ssi log info "Installing fuzzycd"
ssi install bin https://github.com/DannyBen/fuzzycd/releases/latest/download/fuzzycd

cat <<'EOF' | ssi install startup --shell bash --name fuzzycd.bashrc -
if command -v fuzzycd >/dev/null 2>&1; then
  source "$(command -v fuzzycd)"
fi
EOF

cat <<'EOF' | ssi install startup --shell zsh --name fuzzycd.zshrc -
if command -v fuzzycd >/dev/null 2>&1; then
  source "$(command -v fuzzycd)"
fi
EOF

ssi log info "fuzzycd -v : $(fuzzycd -v)"
