name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  ubuntu_approval:
    name: Approval on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install fzf
      run: sudo apt install -y fzf
    - name: Run approval tests
      run: test/approve

  macos_approval:
    name: Approval on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install fzf
      run: brew install fzf
    - name: Run approval tests
      run: test/approve

  ubuntu_acceptance:
    name: Acceptance on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install fzf
      run: sudo apt install -y fzf
    - name: Install Shellkin
      run: curl -Ls get.dannyb.co/shellkin/setup | bash
    - name: Run acceptance tests
      run: shellkin

  macos_acceptance:
    name: Acceptance on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install fzf
      run: brew install fzf
    - name: Install Shellkin
      run: curl -Ls get.dannyb.co/shellkin/setup | bash
    - name: Run acceptance tests
      run: shellkin

  ubuntu_setup:
    name: Setup on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run setup approval tests
      run: test/approve_setup

  macos_setup:
    name: Setup on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Upgrade the outdated bash
      run: brew install bash
    - name: Run setup approval tests
      run: test/approve_setup

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run shellcheck tests
      run: shellcheck setup fuzzycd && echo PASS
